sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mayumi0612/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mayumi0612/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-531484069390"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
